stages:
  - test
  - pages

lint:
  stage: test
  image: python:3.14
  before_script:
    - pip install nox
  script:
    - nox -s lint

test:
  stage: test
  image: python:3.14
  before_script:
    - pip install nox
  script:
    - nox -s test

build_pages:
  stage: pages
  image: python:3.14
  before_script:
    - pip install nox
  script:
    - nox -s gendoc
  pages:
    publish: build/html/
